SET MODE MySQL;

CREATE TABLE IF NOT EXISTS CLIENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    INSTANCE_ID BINARY(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    LAST_HEARTBEAT_TIMESTAMP TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS JOB (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ORG_ID INTEGER NULL,
    STATUS VARCHAR(25) NOT NULL,
    REQUESTED_AT TIMESTAMP(6) NOT NULL,
    STARTED_AT TIMESTAMP(6) NULL,
    COMPLETED_AT TIMESTAMP(6) NULL,
    ERROR_MESSAGE LONGTEXT NULL,

    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
