CREATE TABLE IF NOT EXISTS CLIENT (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    LAST_HEARTBEAT_TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS JOB (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(25) NOT NULL,
    REQUESTED_AT TIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP NULL,
    COMPLETED_AT TIMESTAMP NULL,
    ERROR_MESSAGE LONGTEXT NULL,

    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);